author: Frank Montalvo Ochoa

name: bloc_provider
description: Bloc Provider.
version: 0.0.3

homepage: https://www.ivortec.com

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
